"""Recreate lost migration

Revision ID: 2463c03d680b
Revises: 866aaa7d4fba
Create Date: 2025-08-01 02:37:25.361800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2463c03d680b'
down_revision: Union[str, Sequence[str], None] = '866aaa7d4fba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE INDEX IF NOT EXISTS idx_doc_source ON chat_sessions (source_id);")
    op.execute("CREATE INDEX IF NOT EXISTS idx_doc_user ON chat_sessions (user_id);")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_doc_user', table_name='chat_sessions')
    op.drop_index('idx_doc_source', table_name='chat_sessions')
    # ### end Alembic commands ###
