"""add public_url column to pdf_files

Revision ID: 8db75112370e
Revises: 8f0f0d32ccb2
Create Date: 2025-07-19 10:26:20.458318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8db75112370e'
down_revision: Union[str, Sequence[str], None] = '8f0f0d32ccb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pdf_files', sa.Column('public_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pdf_files', 'public_url')
    # ### end Alembic commands ###
