"""initial schema

Revision ID: ca548d54b8a9
Revises: 
Create Date: 2025-07-18 14:50:32.334097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca548d54b8a9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('llm_model', sa.String(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('chat_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('feature_type', sa.Enum('pdf', 'csv', 'api', 'web', name='featuretypeenum'), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_sessions', 'chat_sessions', ['user_id'], unique=False)
    op.create_table('csv_datasets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('supabase_path', sa.String(), nullable=False),
    sa.Column('embedding_status', sa.Enum('pending', 'completed', 'failed', name='statusenum'), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_csv_user', 'csv_datasets', ['user_id'], unique=False)
    op.create_table('pdf_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('supabase_path', sa.String(), nullable=False),
    sa.Column('embedding_status', sa.Enum('pending', 'completed', 'failed', name='statusenum'), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pdf_user', 'pdf_files', ['user_id'], unique=False)
    op.create_table('web_scraped_pages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('page_title', sa.String(), nullable=True),
    sa.Column('embedding_status', sa.Enum('pending', 'completed', 'failed', name='statusenum'), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_web_user', 'web_scraped_pages', ['user_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('user', 'ai_agent', name='roleenum'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_session_messages', 'chat_messages', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_session_messages', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index('idx_web_user', table_name='web_scraped_pages')
    op.drop_table('web_scraped_pages')
    op.drop_index('idx_pdf_user', table_name='pdf_files')
    op.drop_table('pdf_files')
    op.drop_index('idx_csv_user', table_name='csv_datasets')
    op.drop_table('csv_datasets')
    op.drop_index('idx_user_sessions', table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_table('users')
    # ### end Alembic commands ###
